##############
### Common ###
##############

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
  call denite#custom#option('default', 'prompt', '>')

  nnoremap <silent> ,g :<C-u>Denite -buffer-name=search -mode=normal grep<CR>
  " grep結果再表示
  nnoremap <silent> ,r :<C-u>Denite -resume -buffer-name=search<CR>

  call denite#custom#var('grep', 'command', ['pt'])
	call denite#custom#var('grep', 'default_opts',
			\ ['--nogroup', '--nocolor', '--smart-case'])
	call denite#custom#var('grep', 'recursive_opts', [])
	call denite#custom#var('grep', 'pattern_opt', [])
	call denite#custom#var('grep', 'separator', ['--'])
	call denite#custom#var('grep', 'final_opts', [])

  call denite#custom#map('insert', 'jj', '<denite:enter_mode:normal>')
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  map <C-n> :NERDTreeToggle<CR>
'''

# ファイル曖昧検索
[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

# カッコを閉じる
[[plugins]]
repo = 'cohama/lexima.vim'

# resizing of windows
[[plugins]]
repo = 'simeji/winresizer'

# カラースキーマ
[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
  colorscheme molokai
  let g:molokai_original = 1
  let g:rehash256 = 1
'''

[[plugins]]
repo = 'flazz/vim-colorschemes'

# 非同期補完
[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  if !has('nvim')
    call dein#add('roxma/nvim-yarp')
    call dein#add('roxma/vim-hug-neovim-rpc')
  endif
  let g:deoplete#enable_at_startup = 1
'''

# 構文チェック
[[plugins]]
repo = 'neomake/neomake'
hook_add = '''
  autocmd! BufWritePost * Neomake
'''

# snippets
[[plugins]]
repo = 'SirVer/ultisnips'

[[plugins]]
repo = 'honza/vim-snippets'

# terminal
[[plugins]]
repo = 'kassio/neoterm'
hook_add = '''
  let g:neoterm_autoinsert = 1
  let g:neoterm_default_mod='belowright'
  tnoremap <silent> jj <C-\><C-n><C-w>
  nnoremap <silent> ,t :Tnew<CR><C-w>
'''


################
### Language ###
################

[[plugins]]
repo = 'fatih/vim-go'
hook_add = '''
  let g:go_highlight_functions = 1
  let g:go_highlight_methods = 1
  let g:go_highlight_structs = 1
  let g:go_highlight_extra_types = 1
  let g:go_highlight_operators = 1
  let g:go_highlight_function_calls = 1
  let g:go_highlight_types = 1
  let g:go_highlight_fields = 1

"  let g:syntastic_mode_map = { 'mode': 'passive',
"      \ 'active_filetypes': ['go'] }
"  let g:syntastic_go_checkers = ['go', 'golint']
"  let g:neomake_go_errcheck_maker = {
"      \ 'append_file': 0,
"     \ 'errorformat': '%f:%l:%c:\ %m, %f:%l:%c\ %#%m',
"      \ }
"  let g:neomake_go_enabled_makers = ['golint', 'govet', 'errcheck']

  let g:go_metalinter_enabled = ['vet', 'golint', 'errcheck']
  let g:go_metalinter_autosave = 1

  :command Ge GoErrCheck
  :command Gi GoImports
  :command Gc GoCallers
  :command Gif GoIfErr
'''

# nginx syntax highlight
[[plugins]]
repo = 'chr4/nginx.vim'


###########
### Git ###
###########

# git差分をヴィジュアル表示
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  set updatetime=100
'''

[[plugins]]
repo = 'tpope/vim-fugitive'


################
### Markdown ###
################

[[plugins]]
repo = 'plasticboy/vim-markdown'
[[plugins]]
repo = 'kannokanno/previm'
[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = '''
  autocmd BufRead,BufNewFile *.mkd  set filetype=markdown
  autocmd BufRead,BufNewFile *.md  set filetype=markdown
  " 自動で折りたたまないようにする
  let g:vim_markdown_folding_disabled=1
  let g:previm_open_cmd='open -a Safari'
  :command Po PrevimOpen
'''


##############
### Others ###
##############

# google翻訳
[[plugins]]
repo = 'haya14busa/vim-open-googletranslate'
hook_add = '''
  let g:opengoogletranslate#openbrowsercmd = 'electron-open --without-focus'
  vnoremap t :OpenGoogleTranslate<CR>
'''
