# カッコを閉じる
[[plugins]]
repo = 'cohama/lexima.vim'

# 構文チェック
[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'fatih/vim-go'
hook_add = '''
  let g:go_highlight_functions = 1
  let g:go_highlight_methods = 1
  let g:go_highlight_structs = 1
  let g:go_highlight_extra_types = 1
  let g:go_highlight_operators = 1
  let g:go_highlight_function_calls = 1
  let g:go_highlight_types = 1
  let g:go_highlight_fields = 1

  let g:syntastic_mode_map = { 'mode': 'passive',
      \ 'active_filetypes': ['go'] }
  let g:syntastic_go_checkers = ['go', 'golint']
  :command Ge GoErrCheck
  :command Gi GoImports
  :command Gc GoCallers
'''

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'SirVer/ultisnips'

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'flazz/vim-colorschemes'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  map <C-n> :NERDTreeToggle<CR>
'''

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
  call denite#custom#option('default', 'prompt', '>')
  nnoremap <silent> ,g :<C-u>Denite -buffer-name=search -mode=normal grep<CR>
  call denite#custom#map('insert', 'jj', '<denite:enter_mode:normal>')
'''

# カラースキーマ
[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
  colorscheme molokai
  let g:molokai_original = 1
  let g:rehash256 = 1
'''


# 非同期補完
[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  if !has('nvim')
    call dein#add('roxma/nvim-yarp')
    call dein#add('roxma/vim-hug-neovim-rpc')
  endif
  let g:deoplete#enable_at_startup = 1
'''

# git差分をヴィジュアル表示
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  set updatetime=100
'''

# git
[[plugins]]
repo = 'tpope/vim-fugitive'

# ファイル曖昧検索
[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

# aceのシンタックスハイライト
[[plugins]]
repo = 'yosssi/vim-ace'

# terminal
[[plugins]]
repo = 'kassio/neoterm'
hook_add = '''
  tnoremap <silent> jj <C-\><C-n><C-w>
'''
